# =========================
# PostgreSQL (Database)
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three-tier-db
  template:
    metadata:
      labels:
        app: three-tier-db
    spec:
      containers:
        - name: db
          image: three-tier-db
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "three_tier_db"
            - name: POSTGRES_USER
              value: "three_tier_user"
            - name: POSTGRES_PASSWORD
              value: "three_tier_password"
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: three-tier-db
  ports:
    - port: 5432
      targetPort: 5432

# =========================
# Backend (Flask API)
# =========================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three-tier-backend
  template:
    metadata:
      labels:
        app: three-tier-backend
    spec:
      containers:
        - name: backend
          image: three-tier-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DB_NAME
              value: "three_tier_db"
            - name: DB_USER
              value: "three_tier_user"
            - name: DB_PASSWORD
              value: "three_tier_password"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: three-tier-backend
  ports:
    - port: 5000
      targetPort: 5000

# =========================
# Frontend (Nginx + HTML)
# =========================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three-tier-frontend
  template:
    metadata:
      labels:
        app: three-tier-frontend
    spec:
      containers:
        - name: frontend
          image: three-tier-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: three-tier-frontend
spec:
  type: NodePort
  selector:
    app: three-tier-frontend
  ports:
    - port: 80          # service port
      targetPort: 80    # container port
      nodePort: 30080   # port on localhost
